import { supabase } from "@/integrations/supabase/client";

async function getGitHubToken(): Promise<string | null> {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.provider_token ?? null;
}

async function getGitHubUser(token: string): Promise<{ login: string }> {
  const response = await fetch('https://api.github.com/user', {
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });
  if (!response.ok) {
    throw new Error('Failed to fetch GitHub user info. Your token might be invalid.');
  }
  return response.json();
}

async function createOrGetRepo(token: string, name: string, owner: string): Promise<any> {
  try {
    const repoResponse = await fetch(`https://api.github.com/repos/${owner}/${name}`, {
      headers: {
        Authorization: `token ${token}`,
        Accept: 'application/vnd.github.v3+json',
      }
    });
    if (repoResponse.ok) {
      return await repoResponse.json();
    }
    if (repoResponse.status !== 404) {
      const errorData = await repoResponse.json();
      throw new Error(`Could not check for repository: ${errorData.message}`);
    }
  } catch (e: any) {
    throw new Error(`Error checking for repository: ${e.message}`);
  }

  const createResponse = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name,
      description: `Generated by Brimy: ${name}`,
      private: false,
    }),
  });

  if (!createResponse.ok) {
    const errorData = await createResponse.json();
    throw new Error(`Failed to create repository: ${errorData.message}`);
  }
  return createResponse.json();
}

async function pushFileToRepo(
  token: string,
  owner: string,
  repo: string,
  filePath: string,
  content: string,
  commitMessage: string
): Promise<void> {
  const encodedContent = btoa(unescape(encodeURIComponent(content)));

  const getFileSha = async () => {
    try {
      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
        headers: { Authorization: `token ${token}` },
      });
      if (res.ok) {
        const data = await res.json();
        return data.sha;
      }
      return null;
    } catch (e) {
      return null;
    }
  };

  const sha = await getFileSha();

  const body: { message: string; content: string; sha?: string | null } = {
    message: commitMessage,
    content: encodedContent,
  };

  if (sha) {
    body.sha = sha;
  }

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      Authorization: `token ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Failed to push file: ${errorData.message}`);
  }
}

export async function publishToGitHub(repoName: string, fileContent: string): Promise<string> {
  const token = await getGitHubToken();
  if (!token) {
    throw new Error('Not authenticated with GitHub. Please connect your account to publish.');
  }

  const user = await getGitHubUser(token);
  const owner = user.login;

  const sanitizedRepoName = repoName.trim().replace(/[^a-zA-Z0-9-._]/g, '-').toLowerCase() || 'brimy-project';

  const repo = await createOrGetRepo(token, sanitizedRepoName, owner);
  
  const commitMessage = `feat: update project code via Brimy`;
  await pushFileToRepo(token, owner, repo.name, 'index.html', fileContent, commitMessage);

  return repo.html_url;
}