// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xkcnbvcjzezhjaoxojsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY25idmNqemV6aGphb3hvanN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzA2NzQsImV4cCI6MjA3NzE0NjY3NH0.I6xsD0LHiOsuas5VaxU3killUr_aRDx3Xi57WvXeGlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);